Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
stateList = ['y0', 'y1', 'tau']

IparamList = ['p']

ode1 = Transition('y0', 'y1', TransitionType.ODE)

ode2 = Transition('y1', '-(p - 2*5*cos(2*tau))*y0', TransitionType.ODE)

ode3 = Transition('tau', '1', TransitionType.ODE)

model = DeterministicOde(stateList, paramList, ode=[ode1, ode2, ode3])

theta = [1.0, 1.0, 0.0]

p = 15.0

t = numpy.linspace(0, numpy.pi)

model.parameters = [('p',p)]

model.initial_values = (theta, t[0])

solution = model.integrate(t[1::])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 19[0m
[1;32m     15[0m p [38;5;241m=[39m [38;5;241m15.0[39m
[1;32m     17[0m t [38;5;241m=[39m numpy[38;5;241m.[39mlinspace([38;5;241m0[39m, numpy[38;5;241m.[39mpi)
[0;32m---> 19[0m [43mmodel[49m[38;5;241;43m.[39;49m[43mparameters[49m [38;5;241m=[39m [([38;5;124m'[39m[38;5;124mp[39m[38;5;124m'[39m,p)]
[1;32m     21[0m model[38;5;241m.[39minitial_values [38;5;241m=[39m (theta, t[[38;5;241m0[39m])
[1;32m     23[0m solution [38;5;241m=[39m model[38;5;241m.[39mintegrate(t[[38;5;241m1[39m::])

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pygom-0.1.dev1+g88394ee.d20230830-py3.8-linux-x86_64.egg/pygom/model/base_ode_model.py:235[0m, in [0;36mBaseOdeModel.parameters[0;34m(self, parameters)[0m
[1;32m    231[0m             [38;5;28;01mraise[39;00m InputError(err_string [38;5;241m%[39m \
[1;32m    232[0m                              (parameters[38;5;241m.[39msize, [38;5;28mself[39m[38;5;241m.[39mnum_param))
[1;32m    233[0m [38;5;28;01melse[39;00m:
[1;32m    234[0m     [38;5;28;01mraise[39;00m InputError(err_string [38;5;241m%[39m \
[0;32m--> 235[0m                      ([43mparameters[49m[38;5;241;43m.[39;49m[43msize[49m, [38;5;28mself[39m[38;5;241m.[39mnum_param))
[1;32m    237[0m [38;5;66;03m# type checking, making sure that all the different types[39;00m
[1;32m    238[0m [38;5;66;03m# are accepted[39;00m
[1;32m    239[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(parameters[[38;5;241m0[39m], [38;5;28mtuple[39m):

[0;31mAttributeError[0m: 'list' object has no attribute 'size'

